const daily = document.getElementById("daily");
const weekly = document.getElementById("week");
const monthly = document.getElementById("month");
daily.addEventListener("click",dailyfunction);
function dailyfunction(){
     document.getElementById("workh").innerHTML="5hrs";
     document.getElementById("workp").innerHTML="Last Week - 4hrs";
     document.getElementById("playh").innerHTML="1hrs";
     document.getElementById("playp").innerHTML="Last Week - 2hrs";
     document.getElementById("studyh").innerHTML="0hrs";
     document.getElementById("studyp").innerHTML="Last Week - 1hrs";
     document.getElementById("exh").innerHTML="1hrs";
     document.getElementById("exp").innerHTML="Last Week - 1hrs";
     document.getElementById("socialh").innerHTML="1hrs";
     document.getElementById("socialp").innerHTML="Last Week - 3hrs";
     document.getElementById("selfh").innerHTML="0hrs";
     document.getElementById("selfp").innerHTML="Last Week - 1hrs";
     weekly.removeEventListener("click");
     monthly.removeEventListener("click");
};
weekly.addEventListener("click",weeklyfunction);
function weeklyfunction(){
     document.getElementById("workh").innerHTML="32hrs";
     document.getElementById("workp").innerHTML="Last Week - 36hrs";
     document.getElementById("playh").innerHTML="10hrs";
     document.getElementById("playp").innerHTML="Last Week - 8hrs";
     document.getElementById("studyh").innerHTML="4hrs";
     document.getElementById("studyp").innerHTML="Last Week - 7hrs";
     document.getElementById("exh").innerHTML="4hrs";
     document.getElementById("exp").innerHTML="Last Week - 5hrs";
     document.getElementById("socialh").innerHTML="5hrs";
     document.getElementById("socialp").innerHTML="Last Week - 10hrs";
     document.getElementById("selfh").innerHTML="2hrs";
     document.getElementById("selfp").innerHTML="Last Week - 2hrs";
     monthly.removeEventListener("click");
     daily.removeEventListener("click");
};
monthly.addEventListener("click",monthlyfunction);
function monthlyfunction(){
     document.getElementById("workh").innerHTML="103hrs";
     document.getElementById("workp").innerHTML="Last Week - 128hrs";
     document.getElementById("playh").innerHTML="23hrs";
     document.getElementById("playp").innerHTML="Last Week - 29hrs";
     document.getElementById("studyh").innerHTML="13hrs";
     document.getElementById("studyp").innerHTML="Last Week - 19hrs";
     document.getElementById("exh").innerHTML="11hrs";
     document.getElementById("exp").innerHTML="Last Week - 18hrs";
     document.getElementById("socialh").innerHTML="21hrs";
     document.getElementById("socialp").innerHTML="Last Week - 23hrs";
     document.getElementById("selfh").innerHTML="7hrs";
     document.getElementById("selfp").innerHTML="Last Week - 11hrs";
     weekly.removeEventListener("click");
     daily.removeEventListener("click");
};